/**
 * extension/content/llm_scorer.js
 *
 * LLMScorer — AI-Generated Phishing Page Detection
 *
 * Detects phishing pages generated by LLMs (ChatGPT, Claude, Gemini, open-weight
 * models). These pages exhibit statistical regularities: uniform sentence length,
 * zero typos, high urgency phrase density, repetitive DOM structure, and AI
 * metadata artifacts. 900% increase in LLM-generated phishing since Jan 2025
 * (Abnormal Security). SlashNext observed "AI Phishing 2.0" kits on underground
 * forums generating complete credential harvesting pages from a single prompt.
 *
 * Signal architecture:
 *   llm:uniform_sentence_length       +0.30
 *   llm:urgency_phrase_density        +0.25
 *   llm:low_typo_rate_with_cred_form  +0.25
 *   llm:slop_phrase_density           +0.20
 *   llm:repetitive_dom_structure      +0.20
 *   llm:ai_meta_artifacts             +0.15
 *
 * Alert threshold: 0.50 | Block threshold: 0.70
 *
 * @module LLMScorer
 */

'use strict';

/* __IIFE_WRAPPED__ */
(function () {

/* ------------------------------------------------------------------ */
/*  Constants                                                          */
/* ------------------------------------------------------------------ */

const URGENCY_PHRASES = [
  /verify\s+(your\s+)?(identity|account|email)\s+(immediately|now|within)/i,
  /account\s+(has\s+been\s+|will\s+be\s+)?(suspended|locked|restricted|disabled)/i,
  /action\s+required\s+within\s+\d+\s+(hour|minute|day)/i,
  /confirm\s+your\s+(identity|ownership|account)/i,
  /unauthorized\s+(access|activity|login)\s+(detected|attempt)/i,
  /failure\s+to\s+(comply|respond|verify)\s+will\s+result/i,
  /security\s+alert.*immediate/i,
  /your\s+account\s+has\s+been\s+compromised/i,
];

const AI_META_PATTERNS = [
  /generated\s*(by|with|using)\s*(ai|chatgpt|openai|gpt|claude|gemini|llama)/i,
  /\bGPT-[34]\b/i,
  /content[- ]?type.*ai[- ]generated/i,
];

/**
 * AI writing tells derived from stop-slop (github.com/hardikpandya/stop-slop).
 * Inverted from a suppression blocklist into a detection dictionary.
 * Filtered for phishing relevance — excludes creative-writing-only patterns.
 */
const AI_SLOP_PHRASES = [
  // Openers — throat-clearing
  /\bin today'?s (?:digital|rapidly|fast[- ]paced|ever[- ]changing)/i,
  /\bit'?s (?:important|worth noting|crucial) to (?:note|understand|remember)/i,
  /\bi hope this (?:email|message) finds you well/i,
  // Formal register tells
  /\bkindly (?:be advised|note|ensure|verify|confirm)/i,
  /\bplease be advised that\b/i,
  /\bas per (?:our|the|your) (?:records?|policy|conversation)/i,
  /\bwe (?:would like to|wish to) (?:inform|notify|advise) you/i,
  /\bthis (?:serves as|is to) (?:notify|inform|remind)/i,
  // Credential lure formulae
  /\byour account has been (?:temporarily |permanently )?(?:suspended|locked|restricted|limited|compromised|flagged)/i,
  /\bverify your (?:identity|account|information|credentials) (?:to (?:restore|regain|maintain)|by clicking)/i,
  /\bfailure to (?:do so|comply|respond|verify|update) (?:will|may) result in/i,
  /\bfor (?:your|the) (?:security|safety|protection) of your account/i,
  // Emphasis crutches — vague intensifiers LLMs overuse
  /\bdelve (?:into|deeper)\b/i,
  /\btapestry of\b/i,
  /\blandscape of\b/i,
  /\bunlock (?:the (?:full |true )?potential|new possibilities)\b/i,
  /\bseamless(?:ly)? (?:integrate|transition|experience)\b/i,
  /\beverything you need to know\b/i,
  // Structural clichés
  /\bin (?:today'?s|this) (?:article|guide|post),? (?:we|i|you) will\b/i,
  /\blet'?s (?:dive|explore|take a (?:look|closer look|deep dive))\b/i,
  /\bwithout further (?:ado|delay)\b/i,
  // Endings — performative wrap-ups
  /\bthank you for your (?:continued |ongoing )?(?:cooperation|patience|understanding|prompt (?:attention|action))/i,
  /\bdon'?t hesitate to (?:reach out|contact us|get in touch)\b/i,
  /\bwe (?:value|appreciate) your (?:business|trust|cooperation|loyalty)\b/i,
  /\bstay (?:safe|vigilant|informed|tuned) (?:online|out there|and)\b/i,
];

const SLOP_DENSITY_HIGH_THRESHOLD = 2.0;   // hits per 100 words
const SLOP_DENSITY_MODERATE_THRESHOLD = 0.8;
const SLOP_MIN_WORD_COUNT = 30;

const SENTENCE_LENGTH_CV_THRESHOLD = 0.15;
const MIN_SENTENCES_FOR_ANALYSIS = 10;
const URGENCY_DENSITY_THRESHOLD = 3; // per 500 chars
const MIN_WORD_COUNT_TYPO_CHECK = 200;
const REPETITIVE_SIBLING_THRESHOLD = 4;

/**
 * Common English misspelling patterns that humans make but LLMs don't.
 * We check for the ABSENCE of these — LLM text is suspiciously clean.
 */
const COMMON_TYPO_PATTERNS = [
  /\bteh\b/i, /\brecieve\b/i, /\boccured\b/i, /\bseperate\b/i,
  /\bdefinate\b/i, /\baccommodate\b/i, /\boccurrence\b/i,
  /\bneccessary\b/i, /\bgovernement\b/i, /\benviroment\b/i,
  /\bacesss?\b/i, /\badress\b/i, /\bbussiness\b/i, /\bcalender\b/i,
  /\bcommited\b/i, /\bdefinately\b/i, /\bexistance\b/i,
  /\b[a-z]+\s+\1\b/i, // repeated words ("the the")
];

/* ------------------------------------------------------------------ */
/*  Signal Functions                                                    */
/* ------------------------------------------------------------------ */

/**
 * Check if body text has suspiciously uniform sentence lengths.
 * LLM-generated text tends to produce sentences with very low variance
 * in length (CV < 0.15), while human text varies much more.
 */
function checkUniformSentenceLength(bodyText) {
  if (!bodyText) return [];

  // Split into sentences (period, exclamation, question mark)
  const sentences = bodyText
    .split(/[.!?]+/)
    .map(s => s.trim())
    .filter(s => s.length > 10); // Filter fragments

  if (sentences.length < MIN_SENTENCES_FOR_ANALYSIS) return [];

  const lengths = sentences.map(s => s.split(/\s+/).length);
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  if (mean === 0) return [];

  const variance = lengths.reduce((sum, l) => sum + Math.pow(l - mean, 2), 0) / lengths.length;
  const stddev = Math.sqrt(variance);
  const cv = stddev / mean; // Coefficient of variation

  if (cv < SENTENCE_LENGTH_CV_THRESHOLD) {
    return [{
      id: 'llm:uniform_sentence_length',
      weight: 0.30,
      coefficientOfVariation: cv,
      sentenceCount: sentences.length,
      meanLength: mean,
    }];
  }

  return [];
}

/**
 * Check for high density of urgency/fear phrases.
 * LLM phishing pages pack urgency phrases at high density because the
 * generation prompt typically says "make it urgent".
 */
function checkUrgencyPhraseDensity(bodyText) {
  if (!bodyText || bodyText.length < 100) return [];

  let matchCount = 0;
  for (const pattern of URGENCY_PHRASES) {
    const matches = bodyText.match(new RegExp(pattern.source, 'gi'));
    if (matches) matchCount += matches.length;
  }

  // Normalize to per-500-chars
  const density = (matchCount / bodyText.length) * 500;

  if (density >= URGENCY_DENSITY_THRESHOLD) {
    return [{
      id: 'llm:urgency_phrase_density',
      weight: 0.25,
      matchCount,
      density,
    }];
  }

  return [];
}

/**
 * Check if page has credential fields AND suspiciously clean text.
 * Humans naturally make typos; LLM-generated text is perfectly spelled.
 * This signal only fires when credential fields are present (context gate).
 */
function checkLowTypoRateWithCredForm(doc, bodyText) {
  if (!doc || !bodyText) return [];

  // Must have credential fields
  const hasPassword = doc.querySelectorAll('input[type="password"]').length > 0;
  const hasEmail = doc.querySelectorAll('input[type="email"]').length > 0;
  if (!hasPassword && !hasEmail) return [];

  // Must have enough text to analyse
  const words = bodyText.split(/\s+/).filter(w => w.length > 0);
  if (words.length < MIN_WORD_COUNT_TYPO_CHECK) return [];

  // Check for absence of common typo patterns
  const hasTypos = COMMON_TYPO_PATTERNS.some(p => p.test(bodyText));

  if (!hasTypos) {
    return [{
      id: 'llm:low_typo_rate_with_cred_form',
      weight: 0.25,
      wordCount: words.length,
    }];
  }

  return [];
}

/**
 * Check for repetitive DOM structure.
 * LLM-generated HTML tends to produce structurally identical sibling elements
 * (e.g., 5 <div> children each with exactly <h3>+<p>+<a> inside).
 */
function checkRepetitiveDomStructure(doc) {
  if (!doc || !doc.body) return [];

  // Check all container elements for repetitive children
  const containers = doc.querySelectorAll('div, section, main, article, ul, ol');
  let maxRepetition = 0;

  for (const container of containers) {
    const children = Array.from(container.children);
    if (children.length < REPETITIVE_SIBLING_THRESHOLD) continue;

    // Build tag signature for each child
    const signatures = children.map(child => {
      const childTags = Array.from(child.children).map(c => c.tagName).join(',');
      return `${child.tagName}:${childTags}`;
    });

    // Count most common signature
    const counts = {};
    for (const sig of signatures) {
      counts[sig] = (counts[sig] || 0) + 1;
    }
    const maxCount = Math.max(...Object.values(counts));
    if (maxCount > maxRepetition) maxRepetition = maxCount;
  }

  if (maxRepetition >= REPETITIVE_SIBLING_THRESHOLD) {
    return [{
      id: 'llm:repetitive_dom_structure',
      weight: 0.20,
      maxRepetition,
    }];
  }

  return [];
}

/**
 * Check for AI generation metadata artifacts in page source.
 * Some LLM phishing kits leave traces in meta tags or HTML comments.
 */
function checkAiMetaArtifacts(doc) {
  if (!doc) return [];

  // Check meta tags
  const metas = doc.querySelectorAll('meta[name], meta[content]');
  for (const meta of metas) {
    const name = meta.getAttribute('name') || '';
    const content = meta.getAttribute('content') || '';
    const combined = name + ' ' + content;

    if (AI_META_PATTERNS.some(p => p.test(combined))) {
      return [{
        id: 'llm:ai_meta_artifacts',
        weight: 0.15,
        source: 'meta_tag',
        matched: combined.substring(0, 100),
      }];
    }
  }

  // Check HTML comments
  const html = doc.documentElement?.innerHTML || '';
  const comments = html.match(/<!--[\s\S]*?-->/g) || [];
  for (const comment of comments) {
    if (AI_META_PATTERNS.some(p => p.test(comment))) {
      return [{
        id: 'llm:ai_meta_artifacts',
        weight: 0.15,
        source: 'html_comment',
        matched: comment.substring(0, 100),
      }];
    }
  }

  return [];
}

/**
 * Check for AI-typical "slop" phrases — writing tells that LLMs overuse.
 * Derived from stop-slop (github.com/hardikpandya/stop-slop), inverted from
 * a suppression blocklist into a detection dictionary. Scored by density:
 * hits per 100 words. >2.0 = high confidence (+0.20), >0.8 = moderate (+0.10).
 */
function checkSlopPhraseDensity(bodyText) {
  if (!bodyText) return [];

  const words = bodyText.split(/\s+/).filter(w => w.length > 0);
  if (words.length < SLOP_MIN_WORD_COUNT) return [];

  let hits = 0;
  const matched = [];

  for (const pattern of AI_SLOP_PHRASES) {
    const matches = bodyText.match(new RegExp(pattern.source, 'gi'));
    if (matches) {
      hits += matches.length;
      matched.push(pattern.source.substring(0, 40));
    }
  }

  if (hits === 0) return [];

  const density = (hits / words.length) * 100;

  if (density >= SLOP_DENSITY_MODERATE_THRESHOLD) {
    const weight = density >= SLOP_DENSITY_HIGH_THRESHOLD ? 0.20 : 0.10;
    return [{
      id: 'llm:slop_phrase_density',
      weight,
      hits,
      density,
      wordCount: words.length,
      matched: matched.slice(0, 5),
    }];
  }

  return [];
}

/* ------------------------------------------------------------------ */
/*  Risk Scoring                                                       */
/* ------------------------------------------------------------------ */

/**
 * Calculate composite risk score from signal array.
 * @param {Array<{id: string, weight: number}>} signals
 * @returns {{ riskScore: number, signalList: string[] }}
 */
function calculateLlmRiskScore(signals) {
  if (!signals || signals.length === 0) return { riskScore: 0, signalList: [] };

  const riskScore = Math.min(signals.reduce((sum, s) => sum + s.weight, 0), 1.0);
  const signalList = signals.map(s => s.id);

  return { riskScore, signalList };
}

/* ------------------------------------------------------------------ */
/*  Warning Banner                                                     */
/* ------------------------------------------------------------------ */

/**
 * Inject a warning banner into the page.
 */
function injectLlmWarningBanner(riskScore, signals) {
  if (typeof document === 'undefined') return;
  if (document.getElementById('phishops-llm-banner')) return;

  const severity = riskScore >= 0.90 ? 'Critical' : riskScore >= 0.70 ? 'High' : 'Medium';

  const banner = document.createElement('div');
  banner.id = 'phishops-llm-banner';
  banner.setAttribute('style', [
    'position:fixed', 'top:0', 'left:0', 'right:0', 'z-index:2147483647',
    'background:#BF1B1B', 'color:#F5F0E8', 'padding:12px 16px',
    'font-family:system-ui,-apple-system,sans-serif', 'font-size:14px',
    'text-align:center', 'box-shadow:0 2px 8px rgba(0,0,0,0.5)',
  ].join(';'));

  banner.innerHTML = `
    <strong>PhishOps Warning — Suspected AI-Generated Phishing Page</strong>
    <div style="font-size:12px;margin-top:4px;">
      Severity: ${severity} | Risk: ${riskScore.toFixed(2)} |
      Signals: ${signals.map(s => s.id.replace('llm:', '')).join(', ')}
    </div>
    <button id="phishops-llm-dismiss" style="
      position:absolute;top:8px;right:12px;background:none;border:1px solid #F5F0E8;
      color:#F5F0E8;padding:2px 8px;cursor:pointer;font-size:12px;
    ">dismiss</button>
  `;

  document.documentElement.appendChild(banner);

  document.getElementById('phishops-llm-dismiss')?.addEventListener('click', () => {
    banner.remove();
  });
}

/* ------------------------------------------------------------------ */
/*  Main Analysis                                                      */
/* ------------------------------------------------------------------ */

/**
 * Run full LLMScorer analysis on the current page.
 */
function runLlmScorerAnalysis() {
  if (typeof document === 'undefined') return;

  const hostname = globalThis.location?.hostname || '';
  if (!hostname) return;

  const doc = document;
  const bodyText = doc.body?.innerText || doc.body?.textContent || '';

  const sentenceSignals = checkUniformSentenceLength(bodyText);
  const urgencySignals = checkUrgencyPhraseDensity(bodyText);
  const typoSignals = checkLowTypoRateWithCredForm(doc, bodyText);
  const slopSignals = checkSlopPhraseDensity(bodyText);
  const domSignals = checkRepetitiveDomStructure(doc);
  const metaSignals = checkAiMetaArtifacts(doc);

  const allSignals = [
    ...sentenceSignals,
    ...urgencySignals,
    ...typoSignals,
    ...slopSignals,
    ...domSignals,
    ...metaSignals,
  ];

  const { riskScore, signalList } = calculateLlmRiskScore(allSignals);

  if (riskScore < 0.50) return;

  const severity = riskScore >= 0.90 ? 'Critical' : riskScore >= 0.70 ? 'High' : 'Medium';
  const action = riskScore >= 0.70 ? 'blocked' : 'alerted';

  injectLlmWarningBanner(riskScore, allSignals);

  // Emit telemetry
  if (typeof chrome !== 'undefined' && chrome.runtime?.sendMessage) {
    chrome.runtime.sendMessage({
      type: 'LLMSCORER_EVENT',
      payload: {
        eventType: 'LLM_GENERATED_PHISHING_DETECTED',
        riskScore,
        severity,
        signals: signalList,
        url: globalThis.location?.href || '',
        timestamp: new Date().toISOString(),
        action,
      },
    }).catch(() => {});
  }
}

/* ------------------------------------------------------------------ */
/*  Auto-bootstrap                                                     */
/* ------------------------------------------------------------------ */

if (typeof document !== 'undefined' && typeof process === 'undefined') {
  runLlmScorerAnalysis();
}

/* ------------------------------------------------------------------ */
/*  Test export bridge                                                 */
/* ------------------------------------------------------------------ */
// Chrome MV3 content scripts are classic scripts — top-level `export`
// throws SyntaxError. Register public API on a global namespace so
// vitest can side-effect-import and read from the global.

if (typeof globalThis !== 'undefined') {
  globalThis.__phishopsExports = globalThis.__phishopsExports || {};
  globalThis.__phishopsExports['llm_scorer'] = {
    checkUniformSentenceLength,
    checkUrgencyPhraseDensity,
    checkLowTypoRateWithCredForm,
    checkRepetitiveDomStructure,
    checkAiMetaArtifacts,
    checkSlopPhraseDensity,
    calculateLlmRiskScore,
    injectLlmWarningBanner,
    runLlmScorerAnalysis,
  };
}

})();
